#!/usr/bin/env python3
"""Crystal v11.0.0 asset generation: VISUAL MATURITY pass on the approved
v9/v10 gamelist geometry. Footprints unchanged everywhere; the treatment is
rebuilt for a premium editorial feel:

- Left zone: the single white shard is replaced by THREE layered modules with
  breathing room between them (bg shows through): a masthead plate holding the
  marquee, an editorial metadata sheet with a royal-blue spine, and a print
  module for the screenshot. Asymmetric silhouettes, architectural blue
  corners, faint blueprint, halftone edges, paper grain, refined shadows.
- Metadata: description first, then ONE large anchor stat (year), then grouped
  facts with tracked small-caps kickers (genre / players / developer / rating).
- Hero: tighter asymmetric blue atmosphere, crisper contact shadow, one
  restrained gold rim-light arc on the lower-left silhouette. No halo.
- Title: double rule (white hairline + yellow bar), marker display face.
- Rails: unchanged v9.1/v10 treatment (supplied logos), regenerated byte-
  identical."""
import math, os, random
from PIL import Image, ImageDraw, ImageFont, ImageFilter

ART = os.path.expanduser("~/workspace/crystal-esde-theme/theme-src/crystal/art")
RAILS = os.path.join(ART, "rails")
LOGOS = os.path.join(ART, "console_logos")
os.makedirs(RAILS, exist_ok=True)

ROYAL = (18, 58, 178)
DEEP = (10, 32, 120)
NAVY = (10, 26, 92)
INK = (22, 32, 64)
INKDIM = (58, 74, 115)
YELLOW = (255, 214, 10)
WHITE = (255, 255, 255)

random.seed(20260921)

# ------------------------------------------------------------- helpers ---
def halftone(img, box, color, spacing=9, max_r=4.2, fade="right", alpha_max=95):
    x0, y0, x1, y1 = box
    d = ImageDraw.Draw(img, "RGBA")
    for yy in range(y0, y1, spacing):
        for xx in range(x0, x1, spacing):
            span = max(1, (x1 - x0) if fade in ("right", "left") else (y1 - y0))
            if fade == "right":
                t = (xx - x0) / span
            elif fade == "left":
                t = 1 - (xx - x0) / span
            elif fade == "down":
                t = (yy - y0) / span
            else:
                t = 1 - (yy - y0) / span
            t = max(0.0, min(1.0, t))
            r = max_r * t
            if r < 0.7:
                continue
            d.ellipse([xx - r, yy - r, xx + r, yy + r], fill=color + (int(alpha_max * t),))

def blueprint(img, box, color=(16, 52, 160), step=14, alpha=30):
    x0, y0, x1, y1 = box
    d = ImageDraw.Draw(img, "RGBA")
    for xx in range(x0, x1 + 1, step):
        d.line([(xx, y0), (xx, y1)], fill=color + (alpha,), width=1)
    for yy in range(y0, y1 + 1, step):
        d.line([(x0, yy), (x1, yy)], fill=color + (alpha,), width=1)

def grain(img, mask, strength=14, alpha=10):
    n = Image.effect_noise(img.size, strength).convert("L")
    gr = Image.merge("RGBA", (n, n, n, Image.new("L", img.size, alpha)))
    return Image.alpha_composite(img, Image.composite(gr, Image.new("RGBA", img.size, (0, 0, 0, 0)), mask))

def shard_mask(size, poly):
    m = Image.new("L", size, 0)
    ImageDraw.Draw(m).polygon(poly, fill=255)
    return m

FB = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

def tracked_text_img(text, size, color, tracking):
    font = ImageFont.truetype(FB, size)
    widths = []
    for ch in text:
        b = font.getbbox(ch)
        widths.append(b[2] - b[0])
    total = sum(widths) + tracking * (len(text) - 1)
    asc, desc = font.getmetrics()
    img = Image.new("RGBA", (int(total) + 6, asc + desc + 6), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    x = 3
    for ch, w in zip(text, widths):
        d.text((x, 3), ch, font=font, fill=color + (255,))
        x += w + tracking
    return img

def module_base(W, H, poly, shadow_alpha=120, shadow_blur=15, shadow_off=(10, 13)):
    """Transparent canvas + baked offset shadow + white shard body with grain.
    Returns (img, body_layer_with_mask_applied, mask)."""
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    sh = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(sh).polygon([(x + shadow_off[0], y + shadow_off[1]) for x, y in poly],
                               fill=(6, 14, 44, shadow_alpha))
    img = Image.alpha_composite(img, sh.filter(ImageFilter.GaussianBlur(shadow_blur)))
    body = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(body).polygon(poly, fill=WHITE + (238,))
    mask = shard_mask((W, H), poly)
    body = grain(body, mask)
    return img, body, mask

def finish_module(img, body, mask, deco, path):
    img = Image.alpha_composite(img, Image.composite(deco, Image.new("RGBA", img.size, (0, 0, 0, 0)), mask))
    img = Image.alpha_composite(img, body)
    img.save(path)
    print(os.path.basename(path), img.size)

# ------------------------------------------- module A: masthead plate ---
# 470x300. Holds the marquee as a masthead: navy well baked in, tracked
# "NOW SHOWING" kicker, architectural blue corner, short yellow strike.
def gen_masthead():
    W, H = 470, 300
    poly = [(16, 8), (398, 4), (448, 48), (442, 170), (458, 240), (436, 292),
            (34, 288), (12, 238), (22, 120)]
    img, body, mask = module_base(W, H, poly)
    d = ImageDraw.Draw(body, "RGBA")
    # architectural royal-blue corner, top-left
    d.polygon([(12, 10), (196, 4), (152, 88), (18, 100)], fill=ROYAL + (255,))
    d.polygon([(12, 10), (64, 8), (48, 44), (16, 48)], fill=NAVY + (255,))
    # thin blue rules, top-right (clear of the kicker)
    d.line([(375, 26), (445, 20)], fill=ROYAL + (255,), width=3)
    d.line([(381, 36), (441, 31)], fill=ROYAL + (110,), width=2)
    # navy marquee well (the dynamic marquee art sits exactly on this)
    d.rectangle([20, 42, 450, 250], fill=NAVY + (245,))
    # yellow tick at the well's top-right
    d.polygon([(430, 44), (450, 42), (440, 62)], fill=YELLOW + (255,))
    # short restrained yellow strike under the well
    d.polygon([(30, 258), (200, 254), (198, 262), (28, 266)], fill=YELLOW + (255,))
    # tracked kicker, baked (right of the blue corner, clear of it)
    kick = tracked_text_img("NOW SHOWING", 15, ROYAL, 3)
    body.alpha_composite(kick, (210, 12))
    deco = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    halftone(deco, (452, 60, 468, 290), ROYAL, spacing=8, max_r=3.2, fade="right", alpha_max=60)
    blueprint(deco, (300, 258, 440, 290), alpha=26)
    blueprint(deco, (24, 258, 120, 290), alpha=22)
    finish_module(img, body, mask, deco, os.path.join(ART, "lib_mod_masthead.png"))

# ----------------------------------------- module B: metadata sheet ---
# 470x346. Editorial sheet: royal-blue spine, description first, anchor year,
# grouped facts with tracked kickers. Baked hairline rule under the desc.
def gen_meta():
    W, H = 470, 346
    poly = [(10, 6), (452, 0), (464, 60), (448, 220), (458, 300), (420, 340),
            (24, 336), (6, 280), (14, 120)]
    img, body, mask = module_base(W, H, poly)
    d = ImageDraw.Draw(body, "RGBA")
    # royal-blue spine, left edge
    d.polygon([(10, 6), (28, 4), (24, 336), (8, 338)], fill=ROYAL + (255,))
    d.polygon([(10, 6), (17, 5), (15, 337), (9, 338)], fill=NAVY + (255,))
    # small yellow tick on the spine
    d.polygon([(11, 168), (25, 166), (18, 182)], fill=YELLOW + (255,))
    # baked hairline rule under the description (global y 462 -> local 140)
    d.line([(36, 140), (400, 140)], fill=ROYAL + (110,), width=2)
    d.polygon([(36, 136), (52, 136), (48, 144), (36, 144)], fill=YELLOW + (255,))
    deco = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    blueprint(deco, (440, 40, 466, 320), alpha=24)
    halftone(deco, (20, 270, 140, 340), ROYAL, spacing=8, max_r=3.4, fade="up", alpha_max=60)
    halftone(deco, (408, 300, 462, 340), ROYAL, spacing=7, max_r=2.8, fade="down", alpha_max=50)
    finish_module(img, body, mask, deco, os.path.join(ART, "lib_mod_meta.png"))

# ------------------------------------------- module C: print module ---
# 470x260. Screenshot as a print: window punched for the art, blue pinstripe,
# tracked caption baked into the lip, yellow tick.
def gen_shot():
    W, H = 470, 260
    poly = [(24, 6), (440, 0), (464, 40), (452, 180), (458, 240), (30, 254),
            (8, 220), (14, 80)]
    img, body, mask = module_base(W, H, poly)
    d = ImageDraw.Draw(body, "RGBA")
    # blue pinstripe along the top edge
    d.polygon([(24, 6), (440, 0), (438, 7), (26, 13)], fill=ROYAL + (255,))
    # punch the window the screenshot shows through (shot at local 36,12)
    d.rectangle([36, 12, 432, 235], fill=(0, 0, 0, 0))
    # navy offset block bottom-right (print-stack feel)
    d.polygon([(458, 240), (458, 222), (436, 226), (440, 240)], fill=ROYAL + (255,))
    # tracked caption baked into the lip
    kick = tracked_text_img("SCREENSHOT", 13, ROYAL, 3)
    body.alpha_composite(kick, (38, 238))
    # yellow tick on the lip
    d.polygon([(416, 236), (444, 234), (432, 252)], fill=YELLOW + (255,))
    deco = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    halftone(deco, (36, 238, 410, 256), ROYAL, spacing=7, max_r=2.6, fade="down", alpha_max=55)
    finish_module(img, body, mask, deco, os.path.join(ART, "lib_mod_shot.png"))

# ------------------------------------------------- tracked kickers ---
KICKERS = [
    ("released", "RELEASED", 150),
    ("genre", "GENRE", 140),
    ("players", "PLAYERS", 140),
    ("developer", "DEVELOPER", 150),
    ("rating", "RATING", 140),
]

def gen_kickers():
    for slug, text, w in KICKERS:
        img = tracked_text_img(text, 15, ROYAL, 3)
        canvas = Image.new("RGBA", (w, 24), (0, 0, 0, 0))
        canvas.alpha_composite(img, (0, 2))
        p = os.path.join(ART, f"lib_kicker_{slug}.png")
        canvas.save(p)
        print(os.path.basename(p), canvas.size)

# ------------------------------------------------- title double rule ---
def gen_title_rule():
    W, H = 240, 10
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img, "RGBA")
    d.rectangle([0, 1, W, 3], fill=WHITE + (235,))      # white hairline
    d.rectangle([0, 5, W, 9], fill=YELLOW + (255,))     # yellow bar
    img.save(os.path.join(ART, "lib_title_rule.png"))
    print("lib_title_rule.png", img.size)

# ------------------------------------------------------------ rails ---
# Unchanged v9.1/v10 treatment (supplied logos rotated 90deg CCW, zigzag
# royal edge, broken yellow strikes). Regenerated byte-identical.
SYSTEMS = [
    ("dreamcast", "DREAMCAST"), ("gb", "GAME BOY"), ("gba", "GAME BOY ADVANCE"),
    ("gbc", "GAME BOY COLOR"), ("gc", "GAMECUBE"), ("genesis", "GENESIS"),
    ("megadrive", "MEGA DRIVE"), ("n3ds", "NINTENDO 3DS"), ("n64", "NINTENDO 64"),
    ("nds", "NINTENDO DS"), ("nes", "NES"), ("ps2", "PLAYSTATION 2"),
    ("psp", "PSP"), ("psx", "PLAYSTATION"), ("snes", "SNES"), ("steam", "STEAM"),
    ("wii", "WII"), ("wiiu", "WII U"), ("windows", "WINDOWS"), ("xbox", "XBOX"),
    ("xbox360", "XBOX 360"),
]

def tracked_text_v9(name, font, tracking):
    widths = []
    for ch in name:
        b = font.getbbox(ch)
        widths.append(b[2] - b[0])
    total = sum(widths) + tracking * (len(name) - 1)
    asc, desc = font.getmetrics()
    th = asc + desc
    img = Image.new("RGBA", (int(total) + 4, th + 8), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    x = 2
    for ch, w in zip(name, widths):
        d.text((x, 2), ch, font=font, fill=(255, 255, 255, 255))
        x += w + tracking
    return img

def gen_rail(system, name):
    W, H = 76, 912
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    top = (32, 84, 208, 255)
    bot = (12, 40, 140, 255)
    dd = ImageDraw.Draw(img, "RGBA")
    for y in range(H):
        t = y / (H - 1)
        col = tuple(int(top[i] + (bot[i] - top[i]) * t) for i in range(4))
        phase = (y // 28) % 2
        xr = W - (5 if phase else 1)
        dd.line([(0, y), (xr, y)], fill=col)
    d = ImageDraw.Draw(img, "RGBA")
    for y0, y1 in [(36, 220), (260, 420), (470, 640), (690, 876)]:
        d.polygon([(2, y0), (7, y0 + 6), (7, y1), (2, y1 - 6)], fill=YELLOW + (255,))
    halftone(img, (10, 8, 70, 90), WHITE, spacing=7, max_r=3.0, fade="down", alpha_max=50)
    halftone(img, (10, 822, 70, 904), WHITE, spacing=7, max_r=3.0, fade="up", alpha_max=50)
    blueprint(img, (14, 430, 62, 520), color=(140, 170, 255), step=10, alpha=26)
    logo_path = os.path.join(LOGOS, f"{system}.png")
    if os.path.exists(logo_path):
        logo = Image.open(logo_path).convert("RGBA")
        rot = logo.rotate(90, expand=True)
        rw, rh = rot.size
        scale = min(58.0 / rw, 700.0 / rh)
        rot = rot.resize((max(1, int(rw * scale)), max(1, int(rh * scale))), Image.LANCZOS)
        ox, oy = (W - rot.width) // 2 + 4, (H - rot.height) // 2
        white = Image.new("RGBA", rot.size, WHITE + (255,))
        white.putalpha(rot.split()[3])
        img.alpha_composite(white, (ox + 3, oy + 3))
        img.alpha_composite(rot, (ox, oy))
    else:
        size = 44
        font = ImageFont.truetype(FB, size)
        tw = tracked_text_v9(name, font, 10)
        while tw.width > 700 and size > 20:
            size -= 2
            font = ImageFont.truetype(FB, size)
            tw = tracked_text_v9(name, font, 10)
        vert = tw.rotate(90, expand=True)
        ox, oy = (W - vert.width) // 2 + 4, (H - vert.height) // 2
        shade = Image.new("RGBA", vert.size, DEEP + (255,))
        shade.putalpha(vert.split()[3])
        img.alpha_composite(shade, (ox + 3, oy + 3))
        img.alpha_composite(vert, (ox, oy))
    img.save(os.path.join(RAILS, f"{system}.png"))
    return "logo" if os.path.exists(logo_path) else "TEXT-FALLBACK"

# --------------------------------------------- hero elevation ---
# Tighter, asymmetric royal-blue atmosphere (light from upper-left), a
# crisper soft contact shadow, and ONE restrained gold rim-light arc on the
# lower-left of the hero silhouette. No yellow halo.
def gen_hero_blue():
    W, H = 640, 576
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img, "RGBA")
    cx, cy, R = W / 2 - 40, H / 2 - 50, 290
    for r in range(int(R), 0, -2):
        t = r / R
        a = int(56 * (1 - t) ** 1.7)
        d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(46, 96, 220, a))
    img.save(os.path.join(ART, "lib_glow_blue.png"))
    print("lib_glow_blue.png", img.size)

def gen_hero_shadow():
    W, H = 560, 52
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img, "RGBA")
    d.ellipse([40, 8, W - 40, H - 8], fill=(8, 16, 52, 115))
    img = img.filter(ImageFilter.GaussianBlur(9))
    img.save(os.path.join(ART, "lib_shadow_soft.png"))
    print("lib_shadow_soft.png", img.size)

def gen_hero_arc():
    # restrained gold rim light hugging the 520px hero (r260), lower-left
    S = 560
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img, "RGBA")
    c, R = S / 2, 268
    box = [c - R, c - R, c + R, c + R]
    glow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    ImageDraw.Draw(glow, "RGBA").arc(box, start=100, end=165, fill=YELLOW + (60,), width=14)
    img = Image.alpha_composite(img, glow.filter(ImageFilter.GaussianBlur(6)))
    d = ImageDraw.Draw(img, "RGBA")
    d.arc(box, start=102, end=163, fill=YELLOW + (255,), width=5)
    img.save(os.path.join(ART, "lib_hero_arc.png"))
    print("lib_hero_arc.png", img.size)

# --------------------------------------------- bottom gradient ---
def gen_bottom_gradient():
    W, H = 1280, 270
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img, "RGBA")
    for y in range(H):
        t = (y / (H - 1)) ** 1.4
        d.line([(0, y), (W, y)], fill=(8, 20, 80, int(150 * t)))
    img.save(os.path.join(ART, "lib_bottom_gradient.png"))
    print("lib_bottom_gradient.png", img.size)

RETIRED = ["lib_panel.png", "lib_marquee_back.png", "lib_strike_yellow.png",
           "lib_shot_frame.png", "lib_rule_yellow.png", "lib_glow_yellow.png"]

if __name__ == "__main__":
    gen_masthead()
    gen_meta()
    gen_shot()
    gen_kickers()
    gen_title_rule()
    missing = []
    for system, name in SYSTEMS:
        if gen_rail(system, name) != "logo":
            missing.append(system)
    print("rails: 21 | text fallback:", missing if missing else "none")
    gen_hero_blue()
    gen_hero_shadow()
    gen_hero_arc()
    gen_bottom_gradient()
    for name in RETIRED:
        p = os.path.join(ART, name)
        if os.path.exists(p):
            os.remove(p)
            print("retired", name)
